export default {
  DEMO_ACTION: 'DEMO_ACTION',
  DEMO_REQUEST: 'DEMO_REQUEST',
  DEMO_REQUEST_SUCCESS: 'DEMO_REQUEST_SUCCESS',
  DEMO_REQUEST_ERROR: 'DEMO_REQUEST_ERROR',
  SELECT_REGION: 'SELECT_REGION',
  SELECT_SERIAL_NUMBER: 'SELECT_SERIAL_NUMBER',

  LOAD_LINE_CHART_OPTION: 'LOAD_LINE_CHART_OPTION',
  LOAD_LINE_CHART_OPTION_SUCCESS: 'LOAD_LINE_CHART_OPTION_SUCCESS',
  LOAD_LINE_CHART_OPTION_ERROR: 'LOAD_LINE_CHART_OPTION_ERROR',
  RESET_LINE_CHART_OPTION: 'RESET_LINE_CHART_OPTION',

  LOAD_HEAT_MAP_OPTION: 'LOAD_HEAT_MAP_OPTION',
  LOAD_HEAT_MAP_OPTION_SUCCESS: 'LOAD_HEAT_MAP_OPTION_SUCCESS',
  LOAD_HEAT_MAP_OPTION_ERROR: 'LOAD_HEAT_MAP_OPTION_ERROR',
  RESET_HEAT_MAP_OPTION: 'RESET_HEAT_MAP_OPTION',

  LOAD_TILE_IMAGES: 'LOAD_TILE_IMAGES',
  LOAD_TILE_IMAGES_SUCCESS: 'LOAD_TILE_IMAGES_SUCCESS',
  LOAD_TILE_IMAGES_ERROR: 'LOAD_TILE_IMAGES_ERROR',
  RESET_TILE_IMAGES: 'RESET_TILE_IMAGES',

  RESET_ALL_IMAGES: 'RESET_ALL_IMAGES',

  CLICK_HEAT_MAP: 'CLICK_HEAT_MAP',
}

