export default {
  DEMO_ACTION: 'DEMO_ACTION',
  DEMO_REQUEST: 'DEMO_REQUEST',
  DEMO_REQUEST_SUCCESS: 'DEMO_REQUEST_SUCCESS',
  DEMO_REQUEST_ERROR: 'DEMO_REQUEST_ERROR',
  SELECT_REGION: 'SELECT_REGION',

  LOAD_LINE_CHART_OPTION: 'LOAD_LINE_CHART_OPTION',
  LOAD_LINE_CHART_OPTION_SUCCESS: 'LOAD_LINE_CHART_OPTION_SUCCESS',
  LOAD_LINE_CHART_OPTION_ERROR: 'LOAD_LINE_CHART_OPTION_ERROR',
  RESET_LINE_CHART_OPTION: 'RESET_LINE_CHART_OPTION',
}

