export default {
  DEMO_ACTION: 'DEMO_ACTION',
  DEMO_REQUEST : 'DEMO_REQUEST',
  DEMO_REQUEST_SUCCESS : 'DEMO_REQUEST_SUCCESS',
  DEMO_REQUEST_ERROR : 'DEMO_REQUEST_ERROR',
  SELECT_REGION : 'SELECT_REGION',
}

